version: '2.0'
services: 
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ohm-docker.env
    links:
      - memcached
  memcached:
    image: memcached
networks:
  default:
    external:
      name: ogm_default